version: '3.8'

services:
  # ✅ MySQL Database Service
  db:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-my_app_db}
      MYSQL_USER: ${MYSQL_USER:-my_app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-my_app_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "3306:3306"  # Expose MySQL on localhost
    volumes:
      - db_data:/var/lib/mysql  # Data persistence
    networks:
      - library_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

# ✅ Docker Networks
networks:
  library_network:
    driver: bridge

# ✅ Volumes for data persistence
volumes:
  db_data:
